### ISSUE TITLE
Docker auth failing

### ISSUE THREAD

**Issue by gomezzz** [aidotse/PASEOS#174]
# Issue
## Problem Description
https://github.com/aidotse/PASEOS/actions/runs/5479349145/jobs/9981060785

## Expected Behavior
New image

## What Needs to be Done
Update GitHub secrets

## How Can It Be Tested or Reproduced
Probably only successfully after #169 is also fixed? 🤔

**Comment by GabrieleMeoni** [comment]
Pushing is now working.
