### ISSUE TITLE
Removal of actors

### ISSUE THREAD

**Issue by johanos1** [aidotse/PASEOS#21]
# Feature 
Ability to remove actors from the list of known actors if they for some reason disappear from the network.

## Desired Behavior / Functionality
...

## What Needs to Be Done
Function within the Paseos class to remove an actor from the _state.actor list

## How Can It Be Tested
Add and remove, check number of actors in list.

**Comment by gomezzz** [comment]
In #10 I added the ability to empty the list of known actors, is that sufficient? Or would you want to remove individual ones?

**Comment by johanos1** [comment]
I think we need to be able to remove individual users. Think about the case when one node in the network powers off. Then we wouldn't want to transmit/receive from that node anymore but we still want to collaborate with the remaining ones.

**Comment by gomezzz** [comment]
I'll add it while working on #17 :+1:
