### ISSUE TITLE
Double instantiation warning on running tests

### ISSUE THREAD

**Issue by gomezzz** [aidotse/PASEOS#23]
# Issue
## Problem Description
Running tests leads to double instantiation of paseos which throws a warning.

## Expected Behavior
No warning

## What Needs to be Done
Change __init__ or tests so this doesn't trigger a warning.

## How Can It Be Tested or Reproduced
After checking out PR #26
 python .\init_test.py
17:43:55|PASEOS-DEBUG| Setting LogLevel to DEBUG
17:43:55|PASEOS-DEBUG| Loaded module.
17:43:55|PASEOS-DEBUG| Added orbit to actor sat1
17:43:55|PASEOS-DEBUG| Added power device. MaxBattery=10000Ws, CurrBattery=500Ws, ChargingRate=1W to actor sat1
17:43:55|PASEOS-DEBUG| Initializing simulation.
17:43:55|PASEOS-DEBUG| Loading default cfg...
17:43:55|PASEOS-DEBUG| Added orbit to actor sat1
17:43:55|PASEOS-DEBUG| Added power device. MaxBattery=10000Ws, CurrBattery=500Ws, ChargingRate=1W to actor sat1
17:43:55|PASEOS-DEBUG| Initializing simulation.
17:43:55|PASEOS-WARNING| Tried to create another instance of PASEOS simulation.Keeping original one...
17:43:55|PASEOS-DEBUG| Loading default cfg...

As you can see I get this warning. I am not sure if this is a problem or this test actually is to check if this warning is raised.
17:43:55|PASEOS-DEBUG| Added orbit to actor sat1

**Comment by johanos1** [comment]
I cannot reproduce this error.

**Comment by GabrieleMeoni** [comment]
I just launched the test and got a warning, **not an error**, that there was an attempt to instantiate PASESOS twice.

**Comment by gomezzz** [comment]
I fail to reproduce this on my machine

```
$ pytest
==================================================================== test session starts =====================================================================
platform linux -- Python 3.10.6, pytest-7.1.3, pluggy-1.0.0
rootdir: /...
collected 8 items                                                                                                                                            

activity_test.py .                                                                                                                                     [ 12%]
check_communication_test.py .                                                                                                                          [ 25%]
eclipse_test.py .                                                                                                                                      [ 37%]
import_test.py .                                                                                                                                       [ 50%]
init_test.py ..                                                                                                                                        [ 75%]
line_of_sight_test.py .                                                                                                                                [ 87%]
power_test.py .                                                                                                                                        [100%]

===================================================================== 8 passed in 1.82s ======================================================================
(paseos) 
```

**Comment by gomezzz** [comment]
@GabrieleMeoni when do you get it?

**Comment by gomezzz** [comment]
(I tested with PR #26 )
