### ISSUE TITLE
Power test fails

### ISSUE THREAD

**Issue by johanos1** [aidotse/PASEOS#25]
# Issue
## Problem Description
The test_power_charging() throws a run-time error:
RuntimeError: bad lexical cast: source type value could not be interpreted as target

## Expected Behavior
Test should pass.

## What Needs to be Done
Don't print the pykep epoch in the eclipse check.

## How Can It Be Tested or Reproduced
Make sure the test does not fail.

**Comment by gomezzz** [comment]
It works on the CI and github as seen here
https://github.com/aidotse/PASEOS/actions/runs/3289918278/jobs/5422056857

Can you tag a branch + commit where this happens to make sure it's reproducible? 

Also where in which line is the error thrown?

**Comment by gomezzz** [comment]
@johanos1 Does it still happen for you in the current version? If so, could you post the above? :)

**Comment by johanos1** [comment]
I cannot reproduce, let's close this. :)
