### ISSUE TITLE
Robustify actor comparison

### ISSUE THREAD

**Issue by johanos1** [aidotse/PASEOS#28]
# Feature
## Desired Behavior / Functionality
The actors are only compared based on their names but there are other distinguishing features too. If an actor is created with completely different parameters other than the name of an existing actor, it will be declined. There is an opportunity to make the comparison more robust.

## What Needs to Be Done
Implement __hash()__ for the actor classes.

## How Can It Be Tested
- Create two actors with the same parameters and make sure they get the same hash
- Create two actors with same parameters except one, make sure hashes are different.

**Comment by gomezzz** [comment]
@johanos1 Hmmm, thinking about this now, let's say I get an actor in my known actors. Now it gets updated a little later. Shouldn't the actor comparison be only name / ID based? It's still the same actor just at different times? 🤔 At least for `sat1_at_t0 == sat1_at_t1` should be `True`, I think? Wouldn't be with the hash though?

**Comment by johanos1** [comment]
We can make a custom __hash__ if we want to disregard, e.g., time. But yea, I am not sure this feature is necessary. Maybe close?

**Comment by gomezzz** [comment]
Closed for now, can re-open if needed
