### ISSUE TITLE
Thermal Model

### ISSUE THREAD

**Issue by gomezzz** [aidotse/PASEOS#31]
# Feature
## Desired Behavior / Functionality
Simulate the thermal constraints of running something 

## What Needs to Be Done
TBD

## How Can It Be Tested
TBD

**Comment by gomezzz** [comment]
So, what is the simplest, first model we could do? Maybe something like:
- Have an actor-specific maximum operational temperature
- Have a constant positive heat dissipation rate in eclipse
- While in sun, reduce or negative heat dissipation rate?
- Depending on power consumption add heat?

What do you think, @GabrieleMeoni ?

**Comment by gomezzz** [comment]
For easier understanding, I made a diagram explaining all the variables, I think the linearized version of single node model may be good starting point 
![Thermal model drawio](https://user-images.githubusercontent.com/2656685/207892259-8163c13b-4e5a-4877-9e86-ca5c844bf0a6.png)

**Comment by johanos1** [comment]
This seems to be related also to #33 ?

**Comment by gomezzz** [comment]
> This seems to be related also to #33 ?

Not quite. Radiation in the other issue refers more the particle events, see [here](https://llis.nasa.gov/lesson/824/) (I'll add the link to #33)
