### ISSUE TITLE
Automatic clock

### ISSUE THREAD

**Issue by gomezzz** [aidotse/PASEOS#34]
# Feature
## Desired Behavior / Functionality
Right now, the user has to be specify that time has passed by calling some like 

```Python
sim.advance_time(someTime)
```

However, as paseos is meant to run on edge devices (or emulations thereof) it would make a lot of sense to track this automatically by default using the local devices clock and only optionally provide the user the capability to diverge from that?

## What Needs to Be Done
- [x] When starting paseos, get system clock and set local actor time based on that
- [x] Decide carefully on which function calls the user needs to provide the time and on which we just take local
- [x] When ever we perform any activity update local actor time and (simulation, i.e. power, etc. and whatever other constraints we model)

## How Can It Be Tested
- [x] Write a test comparing actor time to local and checking that activities take the time they actually take

**Comment by gomezzz** [comment]
@johanos1 I think we mostly resolved this with #36 ? Should we close or is there anything from the description that we should still add?

**Comment by gomezzz** [comment]
> Are we updating the clock outside of the activities at all?

Yea that is a bit the question. So back when we were discussing this, we wanted to allow users to use a "free-time" mode without the automatic clock if they want to model faster than real time simulation. I think, this is still possible with `advance_time` and there should be a flag in the activity processor to use it. So improving that feature (and then maybe adding an example for it may make sense?)

With the automatic clock, there should be no update outside. Though, the user could technically call advance_time, I think, to wait for some time basically?

So, maybe we strike: 
> When starting paseos, get system clock and set local actor time based on that

Because now you can choose the time which makes more sense?

>  Decide carefully on which function calls the user needs to provide the time and on which we just take local
> When ever we perform any activity update local actor time and (simulation, i.e. power, etc. and whatever other constraints we model)
> Write a test comparing actor time to local and checking that activities take the time they actually take

This is taken care of I think?

**Comment by johanos1** [comment]
> Yea that is a bit the question. So back when we were discussing this, we wanted to allow users to use a "free-time" mode without the automatic clock if they want to model faster than real time simulation. I think, this is still possible with advance_time and there should be a flag in the activity processor to use it. So improving that feature (and then maybe adding an example for it may make sense?)
>
What do you mean flag in the activity processor? To do advance_time automatically? 
Yes, I think we need to have a good example for this because the local vs global and also the asynchronicity is quite confusing. :)

Just a thought: what happens now if the user calls advance_time() inside an activity?

> With the automatic clock, there should be no update outside. Though, the user could technically call advance_time, I think, to wait for some time basically?
> 
> So, maybe we strike:
> 
> When starting paseos, get system clock and set local actor time based on that
> 
> Because now you can choose the time which makes more sense?
> 
I agree.


> Decide carefully on which function calls the user needs to provide the time and on which we just take local
> When ever we perform any activity update local actor time and (simulation, i.e. power, etc. and whatever other constraints we model)
> Write a test comparing actor time to local and checking that activities take the time they actually take
> 
> This is taken care of I think?
Agreed. Although the tests are implicit as we test that the battery is drained enough.

**Comment by gomezzz** [comment]
> What do you mean flag in the activity processor? To do advance_time automatically?

It is built at the moment so that we stop it from automatically advancing the clock (haven't tested though) and it will need to be exposed to the user somehow.

https://github.com/aidotse/PASEOS/blob/16191c4c6d03dd82e8b4c22066167f3c72fd3fd8/paseos/activities/activity_processor.py#L37

> Just a thought: what happens now if the user calls advance_time() inside an activity?
Chaos :D 

An alternative would also be to just include a "scale factor" that we multiply the advanced time by to allow users to speed up the simulation by a constant factor. This would give them less control but be very easy to implement and we could then make advance_time invisible to users to avoid them messing with it? 🤔 

> Yes, I think we need to have a good example for this because the local vs global and also the asynchronicity is quite confusing. :)
👍 

> Agreed. Although the tests are implicit as we test that the battery is drained enough.
If you have an improvement in mind, please add here #1
