### ISSUE TITLE
pip install error

### ISSUE THREAD

**Issue by johanos1** [aidotse/PASEOS#41]
# Issue
## Problem Description
When installing PASEOS using pip, there are no pykep versions that satisfies the requirements.
If the pykep requirement is removed from setup.py and installed manually, it works.

## Expected Behavior
the PASEOS package to be installed.

## What Needs to be Done
Understand why this happens.

## How Can It Be Tested or Reproduced
Install PASEOS from local repo.

**Comment by gomezzz** [comment]
It's because the pip version of pykep does not support new python version (>=3.8 I think). We should start some installation instructions in our README , I guess, where we detail this?

**Comment by gomezzz** [comment]
I added that in #6 please reopen in case this was not the problem but I am fairly confident
