### ISSUE TITLE
Termination function is executed twice if the constraint function has no return value

### ISSUE THREAD

**Issue by GabrieleMeoni** [aidotse/PASEOS#44]
# Issue
## Problem Description
If the constraint function has no ~~argument~~ return value, the termination function might be executed twice, because activity_runner.stop() might be called twice.

## Expected Behavior
Termination shall be executed once.

## What Needs to be Done
~~Manage return values of constraint_function is activity_runner differently.~~
- [ ] Check whether constraint function return true or false. If not raise exception
- [ ] Double check termination is only called once then

## How Can It Be Tested or Reproduced
~~Current version of the example notebook in #38 will print "TERMINATION" twice if no return value is included in the constrain function.~~
- [ ] Add a test with a broken constraint function and check it raises an exception

**Comment by gomezzz** [comment]
> if no return value is included in the constrain function.
this is however the user misdefining the constraint function. We should check that though somehow 🤔 (ideally without unnecessarily executing the constraint function to avoid computational overhead)

**Comment by gomezzz** [comment]
@GabrieleMeoni Is this still open or fixed?

**Comment by GabrieleMeoni** [comment]
It is fixed until the user returns a value in the constraint function. Otherwise, the problem is still there.  I haven't checked what happens when the function returns false. Please, doublecheck this and open an issue to add to check that the return value is not None.

**Comment by gomezzz** [comment]
I'll change the issue accordingly then
