### ISSUE TITLE
Creating a new example notebook showcasing the communication between two satellites

### ISSUE THREAD

**Issue by GabrieleMeoni** [aidotse/PASEOS#59]
# Feature
## Desired Behavior / Functionality

Creating a new example notebook showcasing two different satellites.

## What Needs to Be Done

* The notebook can improve the current version ([Sentinel2_example_notebook.zip](https://github.com/aidotse/PASEOS/files/10114256/Sentinel2_example_notebook.zip)) of #38 having S2A and S2B (One of them will be removed). 
* Explaining the difference between local and other actors
* Showcasing visualization and explaining differences in displaying the local and current actor
* Finding a smart way to update the non-local actor to emulate what happens in a real-case scenario.

## How Can It Be Tested
* We should be executed by someone who does not know PASEOS and see if they can learn how to use it.
* Visualization and updates shall work correctly.

**Comment by gomezzz** [comment]
Done for #91 #106 #107
