### ISSUE TITLE
Power/Battery Modeling

### ISSUE THREAD

**Issue by gomezzz** [aidotse/PASEOS#8]
# Feature
## Desired Behavior / Functionality
We want to model the power consumption / availability during spacecraft operations. Thus, the following things should be considered:
* Is the spacecraft currently charging (solar power -> in central body's shadow?) (for high accuracy this would need a proper model of solar system ephemerides but we can probably make some simplifications to start)
* Battery level and capacity of the spacecraft
* Power consumption of activity (e.g. training)

## What Needs to Be Done

* Add battery levels and charging rates to actors
* Perform charging in certain interval (TBD)
* Add code to check for eclipse by central body
* Provide below API to user

Suggested user-space functions

### Register activity
Used to register an activity (e.g. train ML model, send data to other actor, etc.)
#### Inputs
* Power consumption [float in Watt] (optional, otherwise specified during activity if e.g. duration dependent) 
* Requres line-of-sight to other satellite [bool]
#### Outputs
N/A

### Perform activity
Used to perform an activity (e.g. train ML model, send data to other actor, etc.)
#### Inputs
* If not specified before: Total power consumption [float in Watt] (user needs to consider duration)
#### Outputs
* Performed successfully [bool] - False if not enough power / line of sight

## How Can It Be Tested
Create a simple actor and let them perform some actions. Should add dedicated tests.

**Comment by GabrieleMeoni** [comment]
Modelling the state of charge of batteries could be tricky. We need to see if there is anything around for some batteries.

**Comment by gomezzz** [comment]
> Modelling the state of charge of batteries could be tricky. We need to see if there is anything around for some batteries.
I thought we'd agreed we just start with a simple linear model and go for something more involved later??

**Comment by johanos1** [comment]
Maybe this is useful? Critical review of on-board capacity estimation techniques for lithium-ion batteries in electric and hybrid electric vehicles (https://www.sciencedirect.com/science/article/abs/pii/S0378775315001457)
